### PR TITLE
Show stderr messages from ocamldebug

### PR DESCRIPTION
**Pull request by db4**
In one of my projects I was able to break ocamldebug itself: in reply to `list` command issued by vscode-ocaml it prints `Uncaught exception: Primitives.Out_of_range` on stderr without `(ocd)` on stdout and vscode-ocaml freezes. While it's not your problem, some diagnostic output would be helpful. I do this the following way: if anything appears on stderr while processing output of a command I show it in the debug window.

This PR is mostly to demonstrate the problem; I would be happy if you implement this better.

### CODE REVIEW

**Comment by hackwaly** [comment]
I put it in log, same as parsing error.

**Comment by db4** [comment]
Not exactly. It's critical error, user should see it unconditionally. If a value is not shown - ok, you can continue to debug. But if the whole session freezes - you probably would like to know why.

**Comment by hackwaly** [comment]
Now it same as "program end". I worry about some stderr message doesn't indicate a critical error.

**Comment by db4** [comment]
Yes, such messages also exist. On the one hand, in

```
C:\Work\>ocamldebug not-existing
        OCaml Debugger version 4.02.3         

(ocd) set loadingmode manual                  
(ocd) goto 0                                  
Loading program... Program not found.         
(ocd)                                         
```

`Program not found.` goes to stderr and is a critical error. You have to terminate. On the other hand,

```
(ocd) list non_existing
No source file for Non_existing. 
(ocd)
```

`No source file for Non_existing.` also goes to stderr but probably isn't critical.

I still think that as a general handler `this.sendEvent(new OutputEvent(chunk));` is enough to diagnose the problem and `this.sendEvent(new TerminatedEvent());` is too much. But in some known cases you can handle stderr specifically (e.g. on any stderr in response to `goto 0` you have to terminate)

**Comment by hackwaly** [comment]
OK. That means we should process stderr output as another kind of command response.

**Comment by hackwaly** [comment]
I think current way is still not the perfect. Remains to do in the future.

**Comment by db4** [comment]
Surely it is not. For the future: success can also be reported on stderr. E.g. `goto 0` prints `Done.` when the file is successfully loaded. Due to that https://github.com/hackwaly/vscode-ocaml/commit/5c31da7af61e202415d3ba1f071ac8a439760696 was broken and I was wrong in

> (e.g. on any stderr in response to goto 0 you have to terminate)

**Pull request merged**
